version: '3'

services:
  nodejs:
    image: node_consulta_credito
    restart: always
    build: .
    ports:
      - 5678:5678
    networks:
      - production-network
    depends_on:
      - db
  db:
    image: mariadb
    expose:
      - 5432
    volumes:
      - ./db_consulta_credito:/var/lib/mysql
    restart: always
    ports:
      - 5432:5432
    networks:
      - production-network
    environment:
      MYSQL_TCP_PORT: 5432
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: consulta_credito

networks:
  production-network:
    driver: bridge
